version: '3'
volumes:
  data:
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: example
      MYSQL_USER: example
      MYSQL_PASSWORD: toor
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"
